version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pet_bank
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine3.19
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgresql://root:password@postgres:5432/pet_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main" ]